# Generated by Django 4.2.9 on 2024-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workwithus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(default='', max_length=100)),
                ('field_of_work', models.CharField(default='', max_length=500)),
                ('desc', models.CharField(default='', max_length=500)),
                ('webap', models.BooleanField(default=False)),
                ('app', models.BooleanField(default=False)),
            ],
        ),
    ]
